language: rust
rust:
  - stable
cache: cargo
before_script:
  - rustup component add clippy
  - rustup component add rustfmt
  - cargo build
script:
  - cargo clippy
  - ./tests/run.sh
  - cargo fmt -- --check
services:
  - postgresql
env:
  - PGQL_DB_HOST=127.0.0.1 PGQL_DB_USER=postgres PGQL_DB_PASSWORD= PGQL_DB_NAME=travis_ci_test
